###
POST http://127.0.0.1:3000/api/v1/users/
Content-Type: application/json

{
  "user": {
      "user_id": 3,
    "firstName": "Admin",
    "lastName": "Admin",
    "username": "admin",
    "password": "iruleall",
    "isAdmin": true,
    "sex": "male",
    "height": 72,
    "weight": 225,
    "age": 25,
    "friends": []
    }
}

###
http://127.0.0.1:3000/api/v1/users/

###
POST http://127.0.0.1:3000/api/v1/users/login
Content-Type: application/json

{
  "username": "cam",
      "password": "trinity"
}

###
http://127.0.0.1:3000/api/v1/users/friends/1

###
http://127.0.0.1:3000/api/v1/workouts/myWorkouts/1

###
POST http://127.0.0.1:3000/api/v1/workouts/
Content-Type: application/json

{
  "workout": {
      "workout_id": 3,
      "exercise": {
        "exercise_id": 3,
        "exercise": "Swimming (Front Crawl)",
        "calorie_index": 2.76
      },
      "user_id": 2,
      "time": 30,
      "calories": 179
    }
}

###
POST http://127.0.0.1:3000/api/v1/exercises/
Content-Type: application/json

{
  "exercise": {
    
      "exercise_id": 3,
      "exercise": "Swimming (Front Crawl)",
      "calorie_index": 2.76
    
  }
 }
 ###

 http://127.0.0.1:3000/api/v1/exercises/